name: cpt-38
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.1
  - arrow-cpp=0.15.1
  - pyarrow=0.15.1
  - thrift
  - ipython
  - pip>=19.2
  - pip:
    - lark-parser
    - mypy
    - pyflakes
    - black
    - pyhdfs
    - pyhive[hive]
